<!-- no html abaixo estamos criando o slider-->
<div class="slick-slider">
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/4e33b32a52ce55de20511d647d6efe5d_marcas-roupas-esp-2-opt_1_.jpg" alt="Imagem1" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/esportes-populares-alemanha-scaled_1.jpg" alt="Imagem2" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/4e33b32a52ce55de20511d647d6efe5d_marcas-roupas-esp-2-opt_1_.jpg" alt="Imagem3" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/esportes-populares-alemanha-scaled_1.jpg" alt="Imagem4" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/4e33b32a52ce55de20511d647d6efe5d_marcas-roupas-esp-2-opt_1_.jpg" alt="Imagem3" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/esportes-populares-alemanha-scaled_1.jpg" alt="Imagem2" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/sport.png" alt="Imagem4" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/download_1.jpg" alt="Imagem2" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/language.png" alt="Imagem2" /></div>
    <div class="item"><img src="http://magentostore.test/media/wysiwyg/download.png" alt="Imagem1" /></div>
</div>
<!-- o script abaixo esta chamando o js para a funcionalidade do slider-->
<script type="text/x-magento-init">
    {
        ".slick-slider" : {
            "Magento_Cms/js/custom_slider": {}
        }
    }
</script>